version: '3'
services:
  backend:
    container_name: backend-food
    build:
      target: runtime
      context: ./
      dockerfile: Dockerfile
    image: food-styles
    volumes:
      - ./Log:/project/Log
    ports:
      - "80:80"
    depends_on:
      - pg_db_food
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "pg_db_food:5432", "--", "dotnet", "FoodStyles.dll"]
    environment:
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_HOST: 'pg_db_food'
      DB_PORT: 5432
      DB_NAME: 'food-style-db'

  pg_db_food:
    container_name: pg_db_food
    image: postgres:12.3
    #    This folder tell docker compose, where postgres data will be stored, before ":" - local folder, after - in the container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'food-style-db'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'